Bump LibreHardwareMonitor and upgrade to Net 6.0
With LibreHardwareMonitor targeting net 6.0, this PR also updates to net
6.0, as net 6.0 is the current LTS and 5.0 won't be supported in half a
year.

For LibreHardwareMonitor, the headlining change is that Alder Lake and
Jasper Lake are better supported. The other changes are [mostly minor][1].

Net 6.0 did bring with it some problems. After building the OhmGraphite
it would fail to start with the following exception:

```plain
System.ServiceProcess.TimeoutException: Time out has expired and the operation has not been completed.
System.ServiceProcess.ServiceController.WaitForStatus
```

The failure is almost certainly due to net 6.0 [trimming granularity][0]
changing from `copyused` to `link`.

However, reverting back to `copyused` didn't fix the issue either. Since
I'm unsure what is causing the issue, trimming has been disabled. This
is a bummer as trimming has a positive impact on file size. This
regression isn't apparent as I've enabled assembly compression, which
technically has a performance cost on startup but since this cost is
amoritized over the machine's uptime, hopefully it won't be too
intolerable.

[0]: https://docs.microsoft.com/en-us/dotnet/core/deploying/trimming/trimming-options#trimming-granularity
[1]: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/compare/1701eb91b2e11d8ccefa31fca27d490134e9df8e...d3a38bf