Fix OhmNvme error with resiliant updates
User received the following exception in their log:

```plain
System.NullReferenceException: Object reference not set to an instance of an object.
   at OhmGraphite.OhmNvme.Update()
```

So the code has been updated avoid eagerly deferencing objects that are
null.